package com.manuelblanco.mobilechallenge.core.designsystem.theme

import androidx.compose.ui.graphics.Color

/**
 * Created by Manuel Blanco Murillo on 25/6/23.
 */

internal val LightColorPrimary = Color(0xFF4651C8)
internal val LightColorOnPrimary = Color(0xFFFFFFFF)
internal val LightColorPrimaryContainer = Color(0xFFE0E0FF)
internal val LightColorOnPrimaryContainer = Color(0xFF000569)
internal val LightColorSecondary = Color(0xFF5C5D72)
internal val LightColorOnSecondary = Color(0xFFFFFFFF)
internal val LightColorSecondaryContainer = Color(0xFFE1E0F9)
internal val LightColorOnSecondaryContainer = Color(0xFF191A2C)
internal val LightColorTertiary = Color(0xFF78536B)
internal val LightColorOnTertiary = Color(0xFFFFFFFF)
internal val LightColorTertiaryContainer = Color(0xFFFFD7EE)
internal val LightColorOnTertiaryContainer = Color(0xFF2E1126)
internal val LightColorError = Color(0xFFBA1A1A)
internal val LightColorErrorContainer = Color(0xFFFFDAD6)
internal val LightColorOnError = Color(0xFFFFFFFF)
internal val LightColorOnErrorContainer = Color(0xFF410002)
internal val LightColorBackground = Color(0xFFFFFBFF)
internal val LightColorOnBackground = Color(0xFF1B1B1F)
internal val LightColorSurface = Color(0xFFFFFBFF)
internal val LightColorOnSurface = Color(0xFF1B1B1F)
internal val LightColorSurfaceVariant = Color(0xFFE3E1EC)
internal val LightColorOnSurfaceVariant = Color(0xFF46464F)
internal val LightColorOutline = Color(0xFF777680)
internal val LightColorInverseOnSurface = Color(0xFFF3F0F4)
internal val LightColorInverseSurface = Color(0xFF303034)
internal val LightColorInversePrimary = Color(0xFFBEC2FF)
internal val LightColorShadow = Color(0xFF000000)
internal val LightColorSurfaceTint = Color(0xFF4651C8)
internal val LightColorOutlineVariant = Color(0xFFC7C5D0)
internal val LightColorScrim = Color(0xFF000000)

internal val DarkColorPrimary = Color(0xFFBEC2FF)
internal val DarkColorOnPrimary = Color(0xFF0B179A)
internal val DarkColorPrimaryContainer = Color(0xFF2B36AF)
internal val DarkColorOnPrimaryContainer = Color(0xFFE0E0FF)
internal val DarkColorSecondary = Color(0xFFC5C4DD)
internal val DarkColorOnSecondary = Color(0xFF2E2F42)
internal val DarkColorSecondaryContainer = Color(0xFF444559)
internal val DarkColorOnSecondaryContainer = Color(0xFFE1E0F9)
internal val DarkColorTertiary = Color(0xFFE7B9D5)
internal val DarkColorOnTertiary = Color(0xFF45263C)
internal val DarkColorTertiaryContainer = Color(0xFF5E3C53)
internal val DarkColorOnTertiaryContainer = Color(0xFFFFD7EE)
internal val DarkColorError = Color(0xFFFFB4AB)
internal val DarkColorErrorContainer = Color(0xFF93000A)
internal val DarkColorOnError = Color(0xFF690005)
internal val DarkColorOnErrorContainer = Color(0xFFFFDAD6)
internal val DarkColorBackground = Color(0xFF1B1B1F)
internal val DarkColorOnBackground = Color(0xFFE4E1E6)
internal val DarkColorSurface = Color(0xFF1B1B1F)
internal val DarkColorOnSurface = Color(0xFFE4E1E6)
internal val DarkColorSurfaceVariant = Color(0xFF46464F)
internal val DarkColorOnSurfaceVariant = Color(0xFFC7C5D0)
internal val DarkColorOutline = Color(0xFF91909A)
internal val DarkColorInverseOnSurface = Color(0xFF1B1B1F)
internal val DarkColorInverseSurface = Color(0xFFE4E1E6)
internal val DarkColorInversePrimary = Color(0xFF4651C8)
internal val DarkColorShadow = Color(0xFF000000)
internal val DarkColorSurfaceTint = Color(0xFFBEC2FF)
internal val DarkColorOutlineVariant = Color(0xFF46464F)
internal val DarkColorScrim = Color(0xFF000000)

internal val seed = Color(0xFF4651C8)